project:
  type: website
  output-dir: docs

website:
  title: "2022 R/Pharma tidymodels Talk"
  navbar:
    left:
      - href: index.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

